# Generated by Django 5.0.4 on 2024-05-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingdocument',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
